[workspace]
members = [
    "crates/keyzen-cli",
    "crates/keyzen-core",
    "crates/keyzen-win",
]
default-members = ["crates/keyzen-cli"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
windows-sys = "0.61"
